"""
VibeForge Scaffold — Writes parsed files to disk and sets up the project.

Takes the list of ParsedFile objects from the parser and creates the actual
directory structure, writes each file, initializes git, and detects project type.
"""

import os
import subprocess
from pathlib import Path
from rich.console import Console
from rich.tree import Tree

from .parser import ParsedFile, count_files

console = Console()


def write_project(
    project_dir: str,
    files: list[ParsedFile],
    auto_git: bool = True,
) -> Path:
    """
    Write all parsed files to disk inside the project directory.

    Args:
        project_dir: Name/path for the project directory
        files: List of ParsedFile objects to write
        auto_git: Whether to initialize a git repo

    Returns:
        Path to the created project directory
    """
    project_path = Path(project_dir).resolve()
    project_path.mkdir(parents=True, exist_ok=True)

    written_files = []

    for f in files:
        file_path = project_path / f.path
        # Create parent directories
        file_path.parent.mkdir(parents=True, exist_ok=True)
        # Write the file
        file_path.write_text(f.content, encoding="utf-8")
        written_files.append(f.path)

    # Initialize git
    if auto_git:
        _init_git(project_path)

    return project_path


def _init_git(project_path: Path):
    """Initialize a git repo with an initial commit."""
    try:
        subprocess.run(
            ["git", "init"],
            cwd=str(project_path),
            capture_output=True,
            text=True,
        )
        subprocess.run(
            ["git", "add", "."],
            cwd=str(project_path),
            capture_output=True,
            text=True,
        )
        subprocess.run(
            ["git", "commit", "-m", "✨ Initial vibe — generated by VibeForge"],
            cwd=str(project_path),
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        # Git not installed — skip silently
        pass


def detect_project_type(files: list[ParsedFile]) -> str:
    """Detect what kind of project was generated."""
    filenames = [f.path.lower() for f in files]
    file_contents = {f.path.lower(): f.content.lower() for f in files}

    if "package.json" in filenames:
        pkg = file_contents.get("package.json", "")
        if "next" in pkg:
            return "nextjs"
        elif "vite" in pkg or "react" in pkg:
            return "react"
        elif "express" in pkg:
            return "node"
        elif "vue" in pkg:
            return "vue"
        elif "svelte" in pkg:
            return "svelte"
        return "node"
    elif "requirements.txt" in filenames or "pyproject.toml" in filenames:
        contents = " ".join(file_contents.values())
        if "flask" in contents:
            return "flask"
        elif "fastapi" in contents:
            return "fastapi"
        elif "django" in contents:
            return "django"
        return "python"
    elif "go.mod" in filenames:
        return "go"
    elif "Cargo.toml" in filenames:
        return "rust"

    return "unknown"


def get_next_steps(project_type: str) -> list[str]:
    """Get suggested next commands based on project type."""
    steps = {
        "nextjs": [
            "npm install",
            "npm run dev",
            "Open http://localhost:3000",
        ],
        "react": [
            "npm install",
            "npm run dev",
            "Open http://localhost:5173",
        ],
        "vue": [
            "npm install",
            "npm run dev",
            "Open http://localhost:5173",
        ],
        "svelte": [
            "npm install",
            "npm run dev",
            "Open http://localhost:5173",
        ],
        "node": [
            "npm install",
            "node index.js",
        ],
        "flask": [
            "pip install -r requirements.txt",
            "python app.py",
            "Open http://localhost:5000",
        ],
        "fastapi": [
            "pip install -r requirements.txt",
            "uvicorn main:app --reload",
            "Open http://localhost:8000",
        ],
        "django": [
            "pip install -r requirements.txt",
            "python manage.py migrate",
            "python manage.py runserver",
        ],
        "python": [
            "pip install -r requirements.txt",
            "python main.py",
        ],
        "go": [
            "go mod tidy",
            "go run .",
        ],
        "rust": [
            "cargo build",
            "cargo run",
        ],
    }
    return steps.get(project_type, ["Check the README.md for instructions"])


def print_file_tree(files: list[ParsedFile], project_name: str):
    """Print a beautiful file tree using Rich."""
    tree = Tree(f"📁 [bold cyan]{project_name}[/bold cyan]")
    
    # Build directory structure
    dirs = {}
    for f in sorted(files, key=lambda x: x.path):
        parts = f.path.split("/")
        current = tree
        for i, part in enumerate(parts):
            if i < len(parts) - 1:
                # Directory
                key = "/".join(parts[: i + 1])
                if key not in dirs:
                    dirs[key] = current.add(f"📂 [blue]{part}[/blue]")
                current = dirs[key]
            else:
                # File
                icon = _get_file_icon(part)
                current.add(f"{icon} [green]{part}[/green]")

    console.print(tree)


def _get_file_icon(filename: str) -> str:
    """Get an emoji icon for a file based on its extension."""
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    icons = {
        "py": "🐍",
        "js": "📜",
        "jsx": "⚛️",
        "ts": "📘",
        "tsx": "⚛️",
        "json": "📋",
        "html": "🌐",
        "css": "🎨",
        "md": "📝",
        "yaml": "⚙️",
        "yml": "⚙️",
        "toml": "⚙️",
        "txt": "📄",
        "sql": "🗄️",
        "sh": "🖥️",
        "dockerfile": "🐳",
        "gitignore": "🔒",
        "env": "🔐",
    }
    return icons.get(ext, "📄")
